stuinfosite-db: 
    restart: always
    container_name: stuinfosite-db
    volumes: 
        - /var/lib/mysql
    environment: 
        - MYSQL_ROOT_PASSWORD=zl
    image: stuinfosite-db
stuinfosite-nginx: 
    restart: always
    container_name: stuinfosite-nginx
    ports: 
        - "80:80"
    links: 
        - stuinfosite:uwsgi
    volumes_from: 
        - stuinfosite
    image: stuinfosite-nginx
stuinfosite: 
    restart: always
    container_name: stuinfosite
    links: 
        - stuinfosite-db:db
    volumes: 
        - /StuInfoSite
    image: stuinfosite